// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Event struct {
	ID             int64
	Name           string
	Venue          string
	City           string
	StartsAt       int64
	Tagline        string
	FromPriceCents int64
	ToPriceCents   int64
	Currency       string
	OnSale         int64
}

type Seat struct {
	ID          int64
	EventID     int64
	Section     string
	SectionRank int64
	RowLabel    string
	SeatNumber  int64
	PriceCents  int64
	HeldBy      string
	HeldAt      int64
	ExpiresAt   int64
	SoldTo      string
	SoldAt      int64
}
