// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: my_holds.sql

package db

import (
	"context"
)

const listMyHolds = `-- name: ListMyHolds :many
SELECT id, held_at, expires_at
FROM seats
WHERE event_id = ?1 AND held_by = ?2 AND sold_to = '' AND id < ?3
ORDER BY id DESC
LIMIT ?4
`

type ListMyHoldsParams struct {
	EventID int64
	Session string
	After   int64
	Limit   int64
}

type ListMyHoldsRow struct {
	ID        int64
	HeldAt    int64
	ExpiresAt int64
}

// The viewer's own holds on one event, newest seat first (Q5): only rows
// whose held_by is this session, so nobody else's hold time is ever read
// out. Expired holds of this session are listed too, flagged inactive.
func (q *Queries) ListMyHolds(ctx context.Context, arg ListMyHoldsParams) ([]ListMyHoldsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyHolds,
		arg.EventID,
		arg.Session,
		arg.After,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyHoldsRow
	for rows.Next() {
		var i ListMyHoldsRow
		if err := rows.Scan(&i.ID, &i.HeldAt, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
