// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_events.sql

package db

import (
	"context"
)

const listEvents = `-- name: ListEvents :many
SELECT id, name, venue, city, starts_at, tagline, from_price_cents, currency
FROM events
WHERE on_sale = 1 AND id < ?1
ORDER BY id DESC
LIMIT ?2
`

type ListEventsParams struct {
	After int64
	Limit int64
}

type ListEventsRow struct {
	ID             int64
	Name           string
	Venue          string
	City           string
	StartsAt       int64
	Tagline        string
	FromPriceCents int64
	Currency       string
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Venue,
			&i.City,
			&i.StartsAt,
			&i.Tagline,
			&i.FromPriceCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
