// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hold_seat.sql

package db

import (
	"context"
)

const holdSeat = `-- name: HoldSeat :execrows
UPDATE seats
SET held_by = ?1, held_at = ?2, expires_at = ?2 + 600
WHERE id = ?3 AND sold_to = 0 AND (held_by = 0 OR expires_at <= ?2)
`

type HoldSeatParams struct {
	User   int64
	Now    int64
	SeatID int64
}

// One statement holds the seat only if, at that moment, it is not sold and
// nobody holds it or its hold has expired (Q6). The hold lasts 600 seconds.
// The caller checks that exactly one row changed (S10).
func (q *Queries) HoldSeat(ctx context.Context, arg HoldSeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, holdSeat, arg.User, arg.Now, arg.SeatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
