// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seat_after.sql

package db

import (
	"context"
)

const countSeats = `-- name: CountSeats :one
SELECT COUNT(*) FROM seats WHERE id = ?
`

// Reads after the claim (W1 allows them): they explain a claim that changed
// nothing, and give back the hold that was taken.
func (q *Queries) CountSeats(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeats, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seatHold = `-- name: SeatHold :one
SELECT held_by, held_at, expires_at, sold_to FROM seats WHERE id = ?
`

type SeatHoldRow struct {
	HeldBy    int64
	HeldAt    int64
	ExpiresAt int64
	SoldTo    int64
}

func (q *Queries) SeatHold(ctx context.Context, id int64) (SeatHoldRow, error) {
	row := q.db.QueryRowContext(ctx, seatHold, id)
	var i SeatHoldRow
	err := row.Scan(
		&i.HeldBy,
		&i.HeldAt,
		&i.ExpiresAt,
		&i.SoldTo,
	)
	return i, err
}
