// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seat_map.sql

package db

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events WHERE id = ?
`

func (q *Queries) CountEvents(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventByID = `-- name: EventByID :one
SELECT id, name, venue, city, starts_at, tagline, from_price_cents, to_price_cents, currency FROM events WHERE id = ?
`

type EventByIDRow struct {
	ID             int64
	Name           string
	Venue          string
	City           string
	StartsAt       int64
	Tagline        string
	FromPriceCents int64
	ToPriceCents   int64
	Currency       string
}

func (q *Queries) EventByID(ctx context.Context, id int64) (EventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventByID, id)
	var i EventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Venue,
		&i.City,
		&i.StartsAt,
		&i.Tagline,
		&i.FromPriceCents,
		&i.ToPriceCents,
		&i.Currency,
	)
	return i, err
}

const listEventSeats = `-- name: ListEventSeats :many
SELECT id, section, section_rank, row_label, seat_number, price_cents, held_by, expires_at, sold_to
FROM seats
WHERE event_id = ?1 AND id < ?2
ORDER BY id DESC
LIMIT ?3
`

type ListEventSeatsParams struct {
	EventID int64
	After   int64
	Limit   int64
}

type ListEventSeatsRow struct {
	ID          int64
	Section     string
	SectionRank int64
	RowLabel    string
	SeatNumber  int64
	PriceCents  int64
	HeldBy      string
	ExpiresAt   int64
	SoldTo      string
}

func (q *Queries) ListEventSeats(ctx context.Context, arg ListEventSeatsParams) ([]ListEventSeatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventSeats, arg.EventID, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventSeatsRow
	for rows.Next() {
		var i ListEventSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.SectionRank,
			&i.RowLabel,
			&i.SeatNumber,
			&i.PriceCents,
			&i.HeldBy,
			&i.ExpiresAt,
			&i.SoldTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
