// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"
)

const clearSignInAttempts = `-- name: ClearSignInAttempts :exec
DELETE FROM sign_in_attempts WHERE key = ?
`

func (q *Queries) ClearSignInAttempts(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, clearSignInAttempts, key)
	return err
}

const saveSignInAttempts = `-- name: SaveSignInAttempts :exec
INSERT INTO sign_in_attempts (key, window_start, failures)
VALUES (?1, ?2, ?3)
ON CONFLICT (key) DO UPDATE SET window_start = excluded.window_start, failures = excluded.failures
`

type SaveSignInAttemptsParams struct {
	Key         string
	WindowStart int64
	Failures    int64
}

func (q *Queries) SaveSignInAttempts(ctx context.Context, arg SaveSignInAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, saveSignInAttempts, arg.Key, arg.WindowStart, arg.Failures)
	return err
}

const signInAttempts = `-- name: SignInAttempts :one
SELECT window_start, failures FROM sign_in_attempts WHERE key = ?
`

type SignInAttemptsRow struct {
	WindowStart int64
	Failures    int64
}

func (q *Queries) SignInAttempts(ctx context.Context, key string) (SignInAttemptsRow, error) {
	row := q.db.QueryRowContext(ctx, signInAttempts, key)
	var i SignInAttemptsRow
	err := row.Scan(&i.WindowStart, &i.Failures)
	return i, err
}
