// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (token_hash, user_id, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	Now       int64
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM auth_sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const sessionUser = `-- name: SessionUser :one
SELECT users.id, users.role
FROM auth_sessions JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_hash = ?1 AND auth_sessions.expires_at > ?2
`

type SessionUserParams struct {
	TokenHash string
	Now       int64
}

type SessionUserRow struct {
	ID   int64
	Role string
}

// The identity hook: a session counts while expires_at is later than now.
func (q *Queries) SessionUser(ctx context.Context, arg SessionUserParams) (SessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, sessionUser, arg.TokenHash, arg.Now)
	var i SessionUserRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}
