// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, created_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, role
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	Now          int64
}

type CreateUserRow struct {
	ID    int64
	Email string
	Role  string
}

// Writes only if no account has this email: two sign-ups with one email
// cannot both succeed (no rows back = the email is taken).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Now,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, role, password_hash FROM users WHERE email = ?
`

type UserByEmailRow struct {
	ID           int64
	Email        string
	Role         string
	PasswordHash string
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}
