// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
)

const accountByID = `-- name: AccountByID :one
SELECT id, email, role FROM users WHERE id = ?
`

type AccountByIDRow struct {
	ID    int64
	Email string
	Role  string
}

// The signed-in user's own account row, by the server-set user id (Q2).
// The password hash is never read.
func (q *Queries) AccountByID(ctx context.Context, id int64) (AccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, accountByID, id)
	var i AccountByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}
